name: Deploy App
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repo code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repo code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run linter
        run: npm run lint
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repo code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: build cache
        uses: actions/cache@v3
        with:
          # See here for caching with `yarn` https://github.com/actions/cache/blob/main/examples.md#node---yarn or you can leverage caching with actions/setup-node https://github.com/actions/setup-node
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - name: Build the app
        run: npm run build


